### ISSUE TITLE
SVG font needs to be installed for text to render properly

### ISSUE THREAD

**Issue by JonEsparaz** [Speedcubing-Canada/speedcubing-canada-logos#2]
Turns out the font used in our logo needs to be installed on your device for the SVGs to render properly.

Example from my iOS device:

![image](https://user-images.githubusercontent.com/48423418/179652299-d4a9f5d4-fe00-4bab-afd1-1db344b58783.png)

We should re-save the SVGs with the text as vector paths (instead of Inkscape's editable text nodes).

**Comment by AlyssaHope** [comment]
@bmetherall do you think you could do this? ^^ I'll need svgs of the logo for some t-shirt, lanyard and banner plans we have :) TIA!!
